# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations
from typing import Annotated, Any, Literal
from pydantic import BaseModel, Field
from datetime import date


class CoverageCityRowOut(BaseModel):
    city_code: Annotated[
        Literal["HCM", "HN"],
        Field(
            alias="cityCode",
            description="Ma thanh pho — bang tra cuu `cities`, KHONG phai ENUM Postgres. Enum nay\nchi de OpenAPI/FE co union type; test `test_openapi_contract` giu no khop\nvoi du lieu seed (them thanh pho moi ma quen them vao day -> test do).",
            title="CityCode",
        ),
    ]
    city_name: Annotated[str, Field(alias="cityName", title="Cityname")]
    schools_total: Annotated[int, Field(alias="schoolsTotal", title="Schoolstotal")]
    schools_with_data: Annotated[
        int, Field(alias="schoolsWithData", title="Schoolswithdata")
    ]


class CoverageFieldRowOut(BaseModel):
    field_code: Annotated[str | None, Field(alias="fieldCode", title="Fieldcode")]
    field_name: Annotated[str, Field(alias="fieldName", title="Fieldname")]
    programs_with_tuition: Annotated[
        int, Field(alias="programsWithTuition", title="Programswithtuition")
    ]


class CoverageTotalsOut(BaseModel):
    schools_total: Annotated[int, Field(alias="schoolsTotal", title="Schoolstotal")]
    schools_with_data: Annotated[
        int, Field(alias="schoolsWithData", title="Schoolswithdata")
    ]
    programs_with_tuition: Annotated[
        int, Field(alias="programsWithTuition", title="Programswithtuition")
    ]
    tuition_records: Annotated[
        int, Field(alias="tuitionRecords", title="Tuitionrecords")
    ]
    sources_cited: Annotated[int, Field(alias="sourcesCited", title="Sourcescited")]


class HealthOut(BaseModel):
    status: Annotated[Literal["ok", "degraded"], Field(title="Status")]
    db: Annotated[Literal["ok", "down"], Field(title="Db")]


class ProgramIncreaseOut(BaseModel):
    program_id: Annotated[str, Field(alias="programId", title="Programid")]
    annual_increase_pct: Annotated[
        float, Field(alias="annualIncreasePct", title="Annualincreasepct")
    ]
    increase_source: Annotated[
        Literal["published_roadmap", "default_estimate"],
        Field(alias="increaseSource", title="IncreaseSourceKind"),
    ]


class RelatedMajorOut(BaseModel):
    slug: Annotated[str, Field(title="Slug")]
    name: Annotated[str, Field(title="Name")]
    n_schools: Annotated[int, Field(alias="nSchools", title="Nschools")]
    min_year1_amount: Annotated[
        int, Field(alias="minYear1Amount", title="Minyear1Amount")
    ]
    max_year1_amount: Annotated[
        int, Field(alias="maxYear1Amount", title="Maxyear1Amount")
    ]


class SchoolOut(BaseModel):
    slug: Annotated[str, Field(title="Slug")]
    name: Annotated[str, Field(title="Name")]
    short_name: Annotated[str | None, Field(alias="shortName", title="Shortname")]
    city_code: Annotated[
        Literal["HCM", "HN"],
        Field(
            alias="cityCode",
            description="Ma thanh pho — bang tra cuu `cities`, KHONG phai ENUM Postgres. Enum nay\nchi de OpenAPI/FE co union type; test `test_openapi_contract` giu no khop\nvoi du lieu seed (them thanh pho moi ma quen them vao day -> test do).",
            title="CityCode",
        ),
    ]
    category: Annotated[
        Literal["cong_lap", "cong_lap_tu_chu", "tu_thuc", "tu_thuc_von_nuoc_ngoai"],
        Field(
            description="Gop `type` + `autonomy_status` cua brief thanh 1 enum (schema.md §3 schools).",
            title="SchoolCategory",
        ),
    ]
    logo_url: Annotated[str | None, Field(alias="logoUrl", title="Logourl")]


class SchoolStatsOut(BaseModel):
    n_programs: Annotated[int, Field(alias="nPrograms", title="Nprograms")]
    min_amount: Annotated[int, Field(alias="minAmount", title="Minamount")]
    min_major_name: Annotated[str, Field(alias="minMajorName", title="Minmajorname")]
    median_amount: Annotated[float, Field(alias="medianAmount", title="Medianamount")]
    max_amount: Annotated[int, Field(alias="maxAmount", title="Maxamount")]
    max_major_name: Annotated[str, Field(alias="maxMajorName", title="Maxmajorname")]
    increase_summary: Annotated[
        str, Field(alias="increaseSummary", title="Increasesummary")
    ]


class SchoolTrackStatOut(BaseModel):
    track: Annotated[
        Literal["dai_tra", "chat_luong_cao", "tien_tien", "quoc_te"],
        Field(
            description="He dao tao — hoc phi chenh 3-5 lan, khong bao gio tron khi tinh trung vi.",
            title="ProgramTrack",
        ),
    ]
    n_programs: Annotated[int, Field(alias="nPrograms", title="Nprograms")]
    min_amount: Annotated[int, Field(alias="minAmount", title="Minamount")]
    min_major_name: Annotated[str, Field(alias="minMajorName", title="Minmajorname")]
    median_amount: Annotated[float, Field(alias="medianAmount", title="Medianamount")]
    max_amount: Annotated[int, Field(alias="maxAmount", title="Maxamount")]
    max_major_name: Annotated[str, Field(alias="maxMajorName", title="Maxmajorname")]


class SourceOut(BaseModel):
    url: Annotated[str, Field(title="Url")]
    doc_type: Annotated[
        Literal["de_an_tuyen_sinh", "thong_bao_hoc_phi", "quy_dinh_nghe", "khac"],
        Field(alias="docType", title="SourceDocType"),
    ]
    published_date: Annotated[
        date | None, Field(alias="publishedDate", title="Publisheddate")
    ]


class TaxonomyChildOut(BaseModel):
    code: Annotated[str, Field(title="Code")]
    name: Annotated[str, Field(title="Name")]
    level: Annotated[int, Field(title="Level")]
    n_majors: Annotated[int, Field(alias="nMajors", title="Nmajors")]
    n_programs: Annotated[int, Field(alias="nPrograms", title="Nprograms")]


class TaxonomyMajorOut(BaseModel):
    slug: Annotated[str, Field(title="Slug")]
    name: Annotated[str, Field(title="Name")]
    code: Annotated[str | None, Field(title="Code")]
    n_schools: Annotated[int, Field(alias="nSchools", title="Nschools")]
    min_year1_amount: Annotated[
        int | None, Field(alias="minYear1Amount", title="Minyear1Amount")
    ]
    max_year1_amount: Annotated[
        int | None, Field(alias="maxYear1Amount", title="Maxyear1Amount")
    ]


class TaxonomyNodeOut(BaseModel):
    code: Annotated[str, Field(title="Code")]
    name: Annotated[str, Field(title="Name")]


class TaxonomyNodeRefOut(BaseModel):
    code: Annotated[str, Field(title="Code")]
    name: Annotated[str, Field(title="Name")]
    level: Annotated[int, Field(title="Level")]


class TaxonomyOut(BaseModel):
    field: TaxonomyNodeOut
    group: TaxonomyNodeOut


class TaxonomySummaryOut(BaseModel):
    n_majors: Annotated[int, Field(alias="nMajors", title="Nmajors")]
    n_programs: Annotated[int, Field(alias="nPrograms", title="Nprograms")]


class TuitionRecordOut(BaseModel):
    program_id: Annotated[str, Field(alias="programId", title="Programid")]
    academic_year: Annotated[str, Field(alias="academicYear", title="Academicyear")]
    amount_per_year: Annotated[int, Field(alias="amountPerYear", title="Amountperyear")]
    is_projected: Annotated[bool, Field(alias="isProjected", title="Isprojected")]
    confidence: Annotated[
        Literal["verified", "published_unverified", "estimated"],
        Field(title="ConfidenceLevel"),
    ]
    source: SourceOut | None


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]
    input: Annotated[Any | None, Field(title="Input")] = None
    ctx: Annotated[dict[str, Any] | None, Field(title="Context")] = None


class YearlyAmountOut(BaseModel):
    academic_year: Annotated[str, Field(alias="academicYear", title="Academicyear")]
    amount_per_year: Annotated[int, Field(alias="amountPerYear", title="Amountperyear")]
    is_projected: Annotated[bool, Field(alias="isProjected", title="Isprojected")]


class CoverageCategoryRowOut(BaseModel):
    category: Annotated[
        Literal["cong_lap", "cong_lap_tu_chu", "tu_thuc", "tu_thuc_von_nuoc_ngoai"],
        Field(
            description="Gop `type` + `autonomy_status` cua brief thanh 1 enum (schema.md §3 schools).",
            title="SchoolCategory",
        ),
    ]
    schools_total: Annotated[int, Field(alias="schoolsTotal", title="Schoolstotal")]
    schools_with_data: Annotated[
        int, Field(alias="schoolsWithData", title="Schoolswithdata")
    ]


class CoverageSchoolRowOut(BaseModel):
    slug: Annotated[str, Field(title="Slug")]
    name: Annotated[str, Field(title="Name")]
    short_name: Annotated[str | None, Field(alias="shortName", title="Shortname")]
    city_code: Annotated[
        Literal["HCM", "HN"],
        Field(
            alias="cityCode",
            description="Ma thanh pho — bang tra cuu `cities`, KHONG phai ENUM Postgres. Enum nay\nchi de OpenAPI/FE co union type; test `test_openapi_contract` giu no khop\nvoi du lieu seed (them thanh pho moi ma quen them vao day -> test do).",
            title="CityCode",
        ),
    ]
    category: Annotated[
        Literal["cong_lap", "cong_lap_tu_chu", "tu_thuc", "tu_thuc_von_nuoc_ngoai"],
        Field(
            description="Gop `type` + `autonomy_status` cua brief thanh 1 enum (schema.md §3 schools).",
            title="SchoolCategory",
        ),
    ]
    n_programs: Annotated[int, Field(alias="nPrograms", title="Nprograms")]
    latest_source_doc_type: Annotated[
        Literal["de_an_tuyen_sinh", "thong_bao_hoc_phi", "quy_dinh_nghe", "khac"]
        | None,
        Field(alias="latestSourceDocType"),
    ]
    latest_source_date: Annotated[
        date | None, Field(alias="latestSourceDate", title="Latestsourcedate")
    ]
    last_updated: Annotated[
        date | None, Field(alias="lastUpdated", title="Lastupdated")
    ]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class MajorOut(BaseModel):
    slug: Annotated[str, Field(title="Slug")]
    name: Annotated[str, Field(title="Name")]
    code: Annotated[str | None, Field(title="Code")]
    taxonomy: TaxonomyOut | None
    aliases: Annotated[list[str], Field(title="Aliases")]
    standard_years: Annotated[int, Field(alias="standardYears", title="Standardyears")]
    requires_practice_license: Annotated[
        bool, Field(alias="requiresPracticeLicense", title="Requirespracticelicense")
    ]
    practice_profession: Annotated[
        str | None, Field(alias="practiceProfession", title="Practiceprofession")
    ]


class ProgramOut(BaseModel):
    id: Annotated[str, Field(title="Id")]
    school_slug: Annotated[str, Field(alias="schoolSlug", title="Schoolslug")]
    major_slug: Annotated[str, Field(alias="majorSlug", title="Majorslug")]
    track: Annotated[
        Literal["dai_tra", "chat_luong_cao", "tien_tien", "quoc_te"],
        Field(
            description="He dao tao — hoc phi chenh 3-5 lan, khong bao gio tron khi tinh trung vi.",
            title="ProgramTrack",
        ),
    ]
    language: Annotated[
        Literal["vi", "en", "vi_en"],
        Field(
            description="Cot `programs.language` la `text` (schema.md §2), khong phai ENUM — nhung\nvan dung enum nay lam kieu Python + nguon cho CHECK constraint.",
            title="ProgramLanguage",
        ),
    ]
    campus: Annotated[str | None, Field(title="Campus")]
    display_name: Annotated[str | None, Field(alias="displayName", title="Displayname")]


class SchoolProgramRowOut(BaseModel):
    program: ProgramOut
    major: MajorOut
    year1: TuitionRecordOut


class SchoolRowOut(BaseModel):
    school: SchoolOut
    stats: SchoolStatsOut


class TaxonomyNodeDetailOut(BaseModel):
    code: Annotated[str, Field(title="Code")]
    name: Annotated[str, Field(title="Name")]
    level: Annotated[int, Field(title="Level")]
    n_majors: Annotated[int, Field(alias="nMajors", title="Nmajors")]
    n_programs: Annotated[int, Field(alias="nPrograms", title="Nprograms")]
    path: Annotated[list[TaxonomyNodeRefOut], Field(title="Path")]
    children: Annotated[list[TaxonomyChildOut], Field(title="Children")]
    majors: Annotated[list[TaxonomyMajorOut], Field(title="Majors")]


class TaxonomyRootsOut(BaseModel):
    fields: Annotated[list[TaxonomyChildOut], Field(title="Fields")]
    unclassified: TaxonomySummaryOut | None


class CoverageOut(BaseModel):
    snapshot_date: Annotated[
        date | None, Field(alias="snapshotDate", title="Snapshotdate")
    ]
    totals: CoverageTotalsOut
    by_city: Annotated[list[CoverageCityRowOut], Field(alias="byCity", title="Bycity")]
    by_category: Annotated[
        list[CoverageCategoryRowOut], Field(alias="byCategory", title="Bycategory")
    ]
    by_field: Annotated[
        list[CoverageFieldRowOut], Field(alias="byField", title="Byfield")
    ]
    schools: Annotated[list[CoverageSchoolRowOut], Field(title="Schools")]


class MajorRowOut(BaseModel):
    program: ProgramOut
    school: SchoolOut
    major: MajorOut
    year1: TuitionRecordOut
    increase: ProgramIncreaseOut | None


class ProgramDetailOut(BaseModel):
    program: ProgramOut
    year1: TuitionRecordOut
    increase: ProgramIncreaseOut | None
    yearly_amounts: Annotated[
        list[YearlyAmountOut], Field(alias="yearlyAmounts", title="Yearlyamounts")
    ]
    total_course: Annotated[int, Field(alias="totalCourse", title="Totalcourse")]
    total_with_license: Annotated[
        int, Field(alias="totalWithLicense", title="Totalwithlicense")
    ]


class ProgramDetailResponseOut(BaseModel):
    school: SchoolOut
    major: MajorOut
    programs: Annotated[list[ProgramDetailOut], Field(title="Programs")]
    related_majors: Annotated[
        list[RelatedMajorOut], Field(alias="relatedMajors", title="Relatedmajors")
    ]


class SchoolDetailResponseOut(BaseModel):
    school: SchoolOut
    track_stats: Annotated[
        list[SchoolTrackStatOut], Field(alias="trackStats", title="Trackstats")
    ]
    programs: Annotated[list[SchoolProgramRowOut], Field(title="Programs")]
